[package]
name = "sim_dag"
version = "0.1.0"
edition = "2024"
publish = ["crates-io"]

[dependencies]
sim = { path = "../sim/sim" }
chrono = "0.4.40"
env_logger = "0.11.8"
log = "0.4.27"
serde_json = "1.0.140"
clap = { version = "4.5.37", features = ["derive"] }

